### PR TITLE
Build Component to display each DApp on its Own Page #18

### LINKED ISSUE #18: Build Component to display each DApp on its Own Page
Once the domain for The DApp Store is ready, we'll want to be able to access information about each DApp at `https://<domain>/<dapp_name>`

We have an awesome domain, so anyone should be able to use that and the DApp name to find information about any given DApp, what it's rank is (if any) and where to access it.

Designs can be found here: https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Discovery?node-id=120%3A1 under the "Profile" screen (ignore the question, we do want this screen). The screen should be accessed by clicking on the DApp from anywhere in the Store, and serve to the correct route. 

Clicking directly on the URL from (for e.g. the Home Screen) should take you directly to the DApp though.

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #18

### CODE REVIEW

**Comment by andytudhope** [comment]
Ok, couple of things.

1. This is what the modal on desktop currently looks like:

Screen Shot 2019-04-26 at 16 33 03

Not sure if you can help fix or if that is one of the things @kstoykov is working on.

2. Trying to load localhost:3000/<dapp_name> manually either does not load the page, or just redirects to home, which is not the effect we're going for - the DApp's profile should appear even if someone manually inputs the URL...

3. Also wondering if the strange misalignment in each DAppListItem is something you inherited from the current sprint?

**Comment by iamonuwa** [comment]
> 2. Also wondering if the strange misalignment in each DAppListItem is something you inherited from the current sprint?

Inherited it.

**Comment by iamonuwa** [comment]
> Ok, couple of things.
> 
> 1. This is what the modal on desktop currently looks like:
> 
> Screen Shot 2019-04-26 at 16 33 03
> 
> Not sure if you can help fix or if that is one of the things @kstoykov is working on.
> 
> 1. Trying to load localhost:3000/<dapp_name> manually either does not load the page, or just redirects to home, which is not the effect we're going for - the DApp's profile should appear even if someone manually inputs the URL...

1. For the modal, I think @kstoykov is working on it.

2. I'll fix the routing to open modal or open page now

**Comment by iamonuwa** [comment]
@corpetty please take a look @andytudhope said your should review and pay bounty if everything is fine as he's currenty away

**Review by StatusSceptre — COMMENTED** [review]
Great submission, thank you for the work!

A few things:
- is the rank supposed to be there, I see the spot where it goes but no inheritance in the modal.
- I have to "back" twice to get out of the dapp back to the main screen.  Is this intended?

**Comment by iamonuwa** [comment]
> Great submission, thank you for the work!
> 
> A few things:
> 
> * is the rank supposed to be there, I see the spot where it goes but no inheritance in the modal.
> * I have to "back" twice to get out of the dapp back to the main screen.  Is this intended?

I had to work with the design provided for the rank.

For the back routing, it will go through that because it redirects to a new page and triggers a modal

**Comment by StatusSceptre** [comment]
> I had to work with the design provided for the rank.

I don't get what you mean?  Are the dapps currently not ranked, and is that rank not able to be passed to the modal?  What are the numbers by the Dapps on the home screen?

**Comment by iamonuwa** [comment]
Unlike the categories, there is no ranking and position data for any of the dapps presently https://github.com/status-im/discover-dapps/blob/develop/src/common/data/dapps.js

**Comment by StatusSceptre** [comment]
ok cool, do you mind adding a comment in here on what will be needed to add that data in when it is available?  I'll go ahead and approve this.

**Comment by iamonuwa** [comment]
Update the position and rank for each of the dapps on the https://github.com/status-im/discover-dapps/blob/develop/src/common/data/dapps.js. I'll gladly fix this if it's ready any time.

**Review by StatusSceptre — APPROVED** [review]

**Comment by StatusSceptre** [comment]
Will await @andytudhope for merging.  He may have additional comments, but at least want him to see this.

**Comment by cryptowanderer** [comment]
Hi @iamonuwa :wave: As you can see, I am still locked out of GH with no recourse, hence the delay here. My apologies for all this.

I am discussing with @kstoykov atm whether we can merge this before end of week and then I will make sure the bounty is paid. Apologies again, and thanks for your patience on this one.

**Comment by iamonuwa** [comment]
> Hi @iamonuwa  As you can see, I am still locked out of GH with no recourse, hence the delay here. My apologies for all this.
> 
> I am discussing with @kstoykov atm whether we can merge this before end of week and then I will make sure the bounty is paid. Apologies again, and thanks for your patience on this one.

No worries, BTW why are you locked out. Hearing for the first time GitHub can actually lock someone out

**Comment by cryptowanderer** [comment]
Haha, no, my phone, laptop and wallet did an African disappearing act all in one go, so cannot get passed the 2FA I set up because my backup codes were on paper in my wallet... Could you check the conflicts in the meantime and see if you can resolve some, as that will make merging easier.

**Comment by iamonuwa** [comment]
> Haha, no, my phone, laptop and wallet did an African disappearing act all in one go, so cannot get passed the 2FA I set up because my backup codes were on paper in my wallet... Could you check the conflicts in the meantime and see if you can resolve some, as that will make merging easier.

Oh! 2FA PITA

**Pull request merged**
