### PR TITLE
Adding BTU-Hotel dapp

### PR DESCRIPTION
**Pull request by appyhour770**
Submitting a Dapp (booking hotels)

### CODE REVIEW

**Comment by andytudhope** [comment]
Hey @appyhour770 - this was a bit slow to load in Africa and, even though I granted it permission when it did load in line with 1102, it then still asks me to create a "connexion". Would you mind telling me what that is? i.e. are you tracking users and what do you do with the address info?

Otherwise seems cool. You sure you want it to be under MARKETPLACES?

**Comment by appyhour770** [comment]
Not sure to be in the MARKETPLACES section, maybe you can classify us in "Tool", I'm opened to your recommendation and classification.

Yes we are using the (ETH) address info that we need to reward the user : after each successfull booking, the user is receiving BTU tokens and we need his adress to do so ...

**Comment by andytudhope** [comment]
I hope you protect them as well as you can, and don't link them directly to personal info in your store.

I'm happy to merge this into the live site, and think that it should probably live under 'Other' for now until we have enough services like it to justify a 'travel and accommodation' category. Please will you submit an actual logo, preferably compressed .png and then I can do the updates manually (the v2 site is being tested on Ropsten atm).

**Comment by appyhour770** [comment]
- Yes we protect them.
- Ok for beeing classified in "Other"
- Find a logo 
btu-hotel png

**Comment by andytudhope** [comment]
Cool cool cool - added: https://github.com/status-im/discover-dapps/commit/7f0212d6ce28abbe1b2d82412cd01e6639d47ab5

**Pull request closed without merging**
