### PR TITLE
Adding Bidali to Dapps

### PR DESCRIPTION
**Pull request by corymsmith**

### CODE REVIEW

**Comment by hesterbruikman** [comment]
@corymsmith Thanks for coming to Status. As you're featuring wallets to open the DApp could you add a reference to Status with a Status badge?

Apologies these were not available yet. You can find them here for the time being: https://github.com/status-im/status.im/issues/300

**Comment by hesterbruikman** [comment]
cc @jeluard @flexsurfer (can't add you as a reviewer for some reason)

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by corymsmith** [comment]
@hesterbruikman No worries, I'll do that today. 

@flexsurfer @jeluard I noticed the "All commits must have a verified GPG signature" check and that it has failed. Do I have to create a new PR and re-commit with GPG keys to have this approved?

**Comment by corymsmith** [comment]
@hesterbruikman I just added the badge Simulator Screen Shot - iPhone XR - 2019-05-02 at 09 58 29

**Comment by hesterbruikman** [comment]
Thank you! @corymsmith

**Comment by corymsmith** [comment]
@hesterbruikman @flexsurfer @jeluard Do you need anything else from me for this or is this waiting on something internally at Status? Just want to make sure I'm not dropping the ball on anything :)

**Comment by jeluard** [comment]
@corymsmith LGTM! @andytudhope does that look good to you?

**Comment by cryptowanderer** [comment]
Hey all. Apologies for the delay @corymsmith - as you can see I have been locked out GH for some time now with no recourse. 

And there are a bunch of merge conflicts now here. I am going to close here and add Bidali myself in the next commit I make. Apologies for the inconvenience.

**Comment by corymsmith** [comment]
No worries @cryptowanderer, any idea when its going live? Would be awesome if you could comment on here and let me know if possible.

**Comment by cryptowanderer** [comment]
Hey @corymsmith Bidali was added in this commit https://github.com/status-im/discover-dapps/commit/4b3ef30483526714f7546a8d75674ebdeb9ecb23 and is now on the live site :+1:

**Comment by corymsmith** [comment]
Amazing thanks!

**Pull request closed without merging**
