### PR TITLE
#31 404 when dap.ps/all and dap.ps/categories requested

### LINKED ISSUE #31: 404 when dap.ps/all and dap.ps/categories requested
When user navigates in DAppStore through Dapp categories to we update URL to `dap.ps/categories` /  `dap.ps/all` (without sending a request) and it's fine.

What happens is that if to navigate back in browser from the Dapp that user opened, - we send GET request to respective URL path and it returns 404 

It's same for Status app and desktop Chrome/FF browser

**Steps to reproduce 1**:
1) Open dap.ps
2) Click on 'Exchanges` (or any other) category
3) Click 'Airswap' to navigate to Dapp's home page
4) Navigate back in browser
**Actual result:** 404 response

**Steps to reproduce 2**:
1) Open dap.ps
2) Click on 'View all ->` at the top-right
3) Click 'Airswap' to navigate to Dapp's home page
4) Navigate back in browser
**Actual result:** 404 response

The best solution would be to navigate to the previous view user was on before DApp was opened. I.e. if `Collectables` category is the one user interested in, - we navigate and reveal the 'Collectables' category. 
As a quick solution (because scenarios below likely to be faced by users) we may redirect `/categories` / `/all` path to main DAapStore page or do not update URL path upon user navigation.

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #31

### CODE REVIEW

**Comment by andytudhope** [comment]
Hey @iamonuwa - this doesn't use the gh-pages-spa that we discussed? Is that because we can get away with this hack, rather than requiring that whole package and script?

I worry about inserting this route, because we want to have a profile screen like is described in this issue: https://github.com/status-im/discover-dapps/issues/18 at `dap.ps/<dapp_name>`...

**Comment by andytudhope** [comment]
And is there a way of selecting the right `category` when you return, so we don't have that `None selected` grey bar at the top?

**Comment by iamonuwa** [comment]
> And is there a way of selecting the right `category` when you return, so we don't have that `None selected` grey bar at the top?

Yes, we can reset to initial category if empty

**Comment by iamonuwa** [comment]
> Hey @iamonuwa - this doesn't use the gh-pages-spa that we discussed? Is that because we can get away with this hack, rather than requiring that whole package and script?
> 
> I worry about inserting this route, because we want to have a profile screen like is described in this issue: #18 at `dap.ps/<dapp_name>`...

We'll need to add the routes. The basename is the solution to this task

**Pull request merged**
