### PR TITLE
Initial setup of linting and basic dependencies

### PR DESCRIPTION
**Pull request by JamesGarethSmith**

### CODE REVIEW

**Comment by jeluard** [comment]
Hey @JamesGarethSmith ! Do you expect reviews of any kind? :)

**Comment by JamesGarethSmith** [comment]
@jeluard No don't worry about it 😄 . I just like to keep things organised like this. 

I noticed the GPG signing requirement when I opened the PR so I've just been setting that up and rebasing over the commits.

I'm going to merge now.

**Comment by jeluard** [comment]
Oh don't worry about GPG signing

**Comment by JamesGarethSmith** [comment]
Ok cool, well I've set it up now and learnt something at least. Thanks

**Pull request merged**
