### PR TITLE
#25 Add a 'Featured DApps' Component to be displayed at the top of th…

### LINKED ISSUE #25: Add a "Featured DApps" Component to be displayed at the top of the Home Screen
Build a new "Featured" component, with custom image cards to be displayed at the top of the home screen according to the designs here: https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Discovery?node-id=120%3A1

### PR DESCRIPTION
**Pull request by iamonuwa**
…e Home Screen

Fixes #25

### CODE REVIEW

**Comment by andytudhope** [comment]
OK, thanks. But there are a number of issues.

1. The Featured DApps must slide horizontally and be arranged such that the 1st one is fully visible, the 2nd just slightly so in order that uses know to swipe left and see others. Currently they stack one below the other on mobile: 

Screen Shot 2019-04-15 at 17 51 41

2. The same grey loading components that currently cover the categories and DApps when loading need to cover the Featured cards - the site must look the same when loading (immediately) as it does eventually (fully loaded with images etc).

In general, I recommend working with an iPhone 5 selected in your web tools, as that is the smallest screen still out there in significant numbers in the wild. Remember, we're mobile first here, then desktop.

**Comment by iamonuwa** [comment]
> OK, thanks. But there are a number of issues.
> 
> 1. The Featured DApps must slide horizontally and be arranged such that the 1st one is fully visible, the 2nd just slightly so in order that uses know to swipe left and see others. Currently they stack one below the other on mobile:
> 
> Screen Shot 2019-04-15 at 17 51 41
> 
> 1. The same grey loading components that currently cover the categories and DApps when loading need to cover the Featured cards - the site must look the same when loading (immediately) as it does eventually (fully loaded with images etc).
> 
> In general, I recommend working with an iPhone 5 selected in your web tools, as that is the smallest screen still out there in significant numbers in the wild. Remember, we're mobile first here, then desktop.

Sweet! I'll fix this now

**Comment by andytudhope** [comment]
From the designs, this is what mobile screens should look like (same horizontal scroll as is applied to the "Recently Added" DApps, for instance)

Screen Shot 2019-04-15 at 17 55 41

**Comment by iamonuwa** [comment]
> From the designs, this is what mobile screens should look like (same horizontal scroll as is applied to the "Recently Added" DApps, for instance)
> 
> Screen Shot 2019-04-15 at 17 55 41

Horizontal slide, I get it now. Will fix it. Shouldn't take much time now

**Comment by iamonuwa** [comment]
@andytudhope from iphone 5 emulator
image

**Comment by andytudhope** [comment]
OK cool :+1: 

1. Let's move "Discover" to the top (and make it just "Discover", not Discover DApps).
2. Change the current title there to "Categories", as in the designs.

Also, I'm worried that you keep force-pushing. As it is, we're missing all of Richard's work here on the "Highest Ranked" part, and voting components.

**Comment by iamonuwa** [comment]
> Also, I'm worried that you keep force-pushing. As it is, we're missing all of Richard's work here on the "Highest Ranked" part, and voting components.

Apologies, am trying to pass the GPG signing. Not sure why its failing. But its been passing before now

**Comment by andytudhope** [comment]
Ah, damn, I merged this without checking that you had fixed the loading components, so that there are 3 new large grey blocks that load at the top of page so that when the screen is ready, it looks exactly like what was being loaded. Would you mind still doing that while you've got it open and working?

**Pull request merged**
